(source "marmalade" "http://marmalade-repo.org/packages/")
(source gnu)
(source melpa)
(source org)

(depends-on "0blayout")
(depends-on "adoc-mode")
(depends-on "async")
(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "flymake-easy")
(depends-on "flymake-jshint")
(depends-on "flymake-yaml")
(depends-on "framemove")
(depends-on "git-commit")
(depends-on "js2-mode")
(depends-on "less-css-mode")
(depends-on "magit")
(depends-on "magit-popup")
(depends-on "markup-faces")
(depends-on "multiple-cursors")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "with-editor")
(depends-on "yaml-mode")
