(source "marmalade" "http://marmalade-repo.org/packages/")
(source melpa)
(source org)

(depends-on "adoc-mode")
(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "flymake-easy")
(depends-on "flymake-jshint")
(depends-on "js2-mode")
(depends-on "less-css-mode")
(depends-on "markup-faces")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "magit")
